#%RAML 1.0
title: api

/users:
  get:
    responses: 
      200:
        headers: 
          Content-Type:
            type: string
            default: application/json; charset=utf-8
        body:
          application/json:
 
